# Generated by Django 3.1.7 on 2021-03-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210313_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('on-sale', 'On Sale'), ('pending', 'Pending'), ('sold', 'Sold')], default=('on-sale', 'On Sale'), max_length=255),
        ),
    ]
