# Generated by Django 3.1.7 on 2021-03-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('on-sale', 'On Sale'), ('pending', 'Pending'), ('sold', 'Sold')], default=('on-sale', 'On Sale'), max_length=255, null=True),
        ),
    ]
