# Generated by Django 3.1.3 on 2021-04-18 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210315_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, verbose_name='Name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default=('inactive', 'Inactive'), max_length=20, null=True, verbose_name='Status')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('logo', models.URLField(max_length=500, null=True, verbose_name='Logo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='assets/images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='store.product')),
            ],
        ),
    ]
