# Generated by Django 3.1.3 on 2021-04-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=100)),
                ('buyer', models.CharField(max_length=100)),
                ('order_number', models.CharField(max_length=120, unique=True)),
                ('delivery_location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('paid', 'paid'), ('processing', 'processing'), ('pending', 'pending'), ('cancelled', 'cancelled'), ('refunded', 'refunded')], default='Undefined', max_length=20)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
